usv_engine:
  maximum_engine_speed_rpm: 2200
  throttle_deadband_percent: 5.0
wind_wave_level:
  wind_resistance_level: 9
  wave_resistance_level: 6
usv_static_info:
  ship_length_m: 10.0
  ship_width_m: 3.0
  displacement_t: 5.0
